<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login user successfully</name>
   <tag></tag>
   <elementGuidId>efe8ecf0-22c3-4c0e-8196-617dcf36824b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-dialog-:r0:']/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.items-center.w-full.gap-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60a2db5f-eb7d-45c1-8732-c50d5c34002d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center w-full gap-2</value>
      <webElementGuid>8d81a650-4fcf-4ea3-8892-47edb263b4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login user successfully</value>
      <webElementGuid>4e69ddc6-cbbc-4a15-8adc-0b2236beaa23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-:r0:&quot;)/div[@class=&quot;flex items-end justify-end min-h-screen pt-4 px-4 pb-10 w-full text-center&quot;]/div[@class=&quot;inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:align-middle max-w-md sm:max-w-lg md:max-w-xl lg:max-w-6xl opacity-100 translate-y-0 sm:scale-100&quot;]/div[@class=&quot;bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4&quot;]/div[@class=&quot;flex items-center w-full gap-2&quot;]</value>
      <webElementGuid>8c99dec9-cacc-4399-8ec6-3ee2e8464a50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-:r0:']/div/div[2]/div/div</value>
      <webElementGuid>2a6898d7-2aad-4b54-ad25-b36612d92a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[10]</value>
      <webElementGuid>0ff0c679-1784-4d41-8511-1cc1c49c7d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::div[10]</value>
      <webElementGuid>02fd49ed-41bb-498c-bd51-af32178ed2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div</value>
      <webElementGuid>48956a4c-e09c-4f3d-a849-3b64f4f57e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Login user successfully' or . = 'Login user successfully')]</value>
      <webElementGuid>3971d362-7c4c-48e7-a7cd-2d1568aefba1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
