<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Wishlist Saya</name>
   <tag></tag>
   <elementGuidId>cd1e6336-e0a3-4107-bd6b-cea43c3410ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-tabs-tab-:r6:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71106191-c0f5-4e4a-af97-a25c76a44c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-cerulean-600 text-cerulean-600 w-1/2 border-b-2 py-4 px-1 text-center text-xl leading-[30px] font-semibold</value>
      <webElementGuid>20c879fe-9d7b-45ab-b2a9-2ac153343783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-tabs-tab-:r6:</value>
      <webElementGuid>cb8a3269-5c2a-4af4-b0b5-b594169e4a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>cfed9a4c-bcef-4c5b-96a1-46e5fc70098f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e98f8ed7-6975-4f68-81cf-cce34de45b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1b9f5362-e6e8-46cc-9a47-8a961e84b8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>009afd54-3fc9-4f1d-8ef0-883e4d5791b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>7e962211-b420-47c5-881c-ab078e0ff18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wishlist Saya</value>
      <webElementGuid>fd1944e0-febf-43ba-9aff-f08cf71453cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-tab-:r6:&quot;)</value>
      <webElementGuid>00c1cbbd-4a9d-4543-a6bf-e195c5c5af73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='headlessui-tabs-tab-:r6:']</value>
      <webElementGuid>2f395e62-afb2-458b-a4f9-2e3670c268c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>f3061928-c0b9-4eb3-b1a4-a5c7af0c6376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktivitas Saya'])[1]/following::button[1]</value>
      <webElementGuid>dc628562-6800-4dea-bae8-35e196a09e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Acara'])[2]/following::button[2]</value>
      <webElementGuid>e693c8b5-ebbf-4a52-a424-867a35c3fd2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a tab'])[1]/preceding::button[1]</value>
      <webElementGuid>3d11068c-39d3-4dff-a623-c81136fd113a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training'])[2]/preceding::button[1]</value>
      <webElementGuid>7476328d-d683-455f-a1f2-244b62c1af1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wishlist Saya']/parent::*</value>
      <webElementGuid>edda8397-8772-431e-b8a0-e2dedda42f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>24e94133-0a98-4639-bd43-936c11ec8cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'headlessui-tabs-tab-:r6:' and @type = 'button' and (text() = 'Wishlist Saya' or . = 'Wishlist Saya')]</value>
      <webElementGuid>e48bf277-ecd3-4ec4-ac4e-0519c5bbef99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
