<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Password Gagal Diubah</name>
   <tag></tag>
   <elementGuidId>88dde2d4-1f36-493b-9414-a155b044c851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/ol/li/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>084d19e3-213b-44db-9fa2-e576b48f5069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password Gagal Diubah</value>
      <webElementGuid>69626efc-09e9-4520-ba65-f1c25bf146d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[1]/ol[1]/li[1]/div[2]/div[1]</value>
      <webElementGuid>13be4314-c614-49bf-a918-f5d89ec48dfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/ol/li/div[2]/div</value>
      <webElementGuid>96cf0916-6545-41cf-a3dd-99a24080c787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrodata Academy'])[2]/preceding::div[1]</value>
      <webElementGuid>00bf4630-5268-495e-9637-2e15004f826f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open menu'])[1]/preceding::div[2]</value>
      <webElementGuid>44b0a295-2474-4ad2-8305-3b41441c312e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password Gagal Diubah']/parent::*</value>
      <webElementGuid>9fb10443-bcdd-4648-911e-04e54d26c435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[2]/div</value>
      <webElementGuid>1ed6d6a9-7750-4af6-b491-f78d1c244960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Password Gagal Diubah' or . = 'Password Gagal Diubah')]</value>
      <webElementGuid>c7c14519-05a5-4ce4-a8bb-f124660bd075</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
