<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Jenis Kelamin</name>
   <tag></tag>
   <elementGuidId>5d4cde69-9d11-4152-a030-5f007b50a0ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;gender&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gender</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ce0f2ec4-463d-485b-b6af-266e9bb0538b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>9a295d0c-ca71-4487-bb0b-569031388f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>34519b20-f615-4bc3-8ab8-0b213888f05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Jenis Kelamin</value>
      <webElementGuid>02b9d066-a20a-4b85-8e4d-245e328a9ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block flex-1 border-0 bg-transparent py-[14px] px-5 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-base sm:leading-6</value>
      <webElementGuid>69c8f8a6-f8bc-4095-94c8-b2a0cbba92b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Jenis KelaminLaki-LakiPerempuan</value>
      <webElementGuid>1f3ba37e-eb5e-40f6-9ddb-24cfa34686ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gender&quot;)</value>
      <webElementGuid>5bd28f36-8e9f-4390-ba18-4a3530b99345</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gender']</value>
      <webElementGuid>2866fc3f-d203-4a9f-966a-1a1c5892ee42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/div/div[2]/div/div[5]/div/div/select</value>
      <webElementGuid>7d493716-e144-4fd8-961d-f29f84661585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>176eaba1-051b-41bf-9090-84966db18582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>beb1a792-51f5-463a-a9c0-83ed8a89f16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4644acca-6402-4537-890a-3255623b1869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gender' and @name = 'gender' and @placeholder = 'Pilih Jenis Kelamin' and (text() = 'Pilih Jenis KelaminLaki-LakiPerempuan' or . = 'Pilih Jenis KelaminLaki-LakiPerempuan')]</value>
      <webElementGuid>acc60741-5a50-4e53-9617-da557a6db41c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
