<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Posisi</name>
   <tag></tag>
   <elementGuidId>7d0cb8e0-af2e-4443-a504-3a4f51ac05f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#job</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='job']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ff96c615-2eac-48bd-bde3-40e812471582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job</value>
      <webElementGuid>752dbf20-b5b7-4dfd-8d55-ed4d06d06dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job</value>
      <webElementGuid>dd1871a5-58e7-477b-8cd5-6a222e6db79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff227d35-a098-439b-bbf9-5e11d314aa86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full px-3 py-[14px] bg-gray-50 border  border-gray-300 rounded-lg</value>
      <webElementGuid>08022336-fb49-4959-90a4-64efb041e20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih PosisiIT Security &amp; PolicyBelum BekerjaLainnyaApplication Developer Jr.Security Operation CenterIT Security OfficerIT Security EngineerQuality AssuranceApplication Developer Sr.</value>
      <webElementGuid>88c70efe-45be-46b3-9a34-9fdfbc211be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job&quot;)</value>
      <webElementGuid>58e87b19-97c2-44c8-922e-7f296658783b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='job']</value>
      <webElementGuid>dfe8c94f-ab67-41b6-afd9-a888ef880033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/div[2]/div[2]/div/div[2]/select</value>
      <webElementGuid>0cc087d9-03bb-4cba-b062-d62571cfaab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::select[1]</value>
      <webElementGuid>46b430ec-a6cf-4ea4-b17a-365b3055bcd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::select[1]</value>
      <webElementGuid>87f00695-1c56-462d-9639-5d53f5e7fc5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footer'])[1]/preceding::select[1]</value>
      <webElementGuid>75c2ae98-3884-4d88-88de-1ffd8817f9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>ba30974f-029d-456b-9170-2add19ff0930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'job' and @name = 'job' and @type = 'text' and (text() = 'Pilih PosisiIT Security &amp; PolicyBelum BekerjaLainnyaApplication Developer Jr.Security Operation CenterIT Security OfficerIT Security EngineerQuality AssuranceApplication Developer Sr.' or . = 'Pilih PosisiIT Security &amp; PolicyBelum BekerjaLainnyaApplication Developer Jr.Security Operation CenterIT Security OfficerIT Security EngineerQuality AssuranceApplication Developer Sr.')]</value>
      <webElementGuid>133e4dba-4ba2-4625-8c0a-e78e79ba713d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
