<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Jurusan</name>
   <tag></tag>
   <elementGuidId>fac33700-bf19-47be-bdb5-18e8481cb84c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='major']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#major</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6fcbfc94-8d40-4311-be6a-46019c409706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>major</value>
      <webElementGuid>734636f0-769e-4fae-b021-e4efb0639872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>major</value>
      <webElementGuid>67769f91-5f6b-4e34-96c4-71b8a4cb843f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full px-3 py-[14px] bg-gray-50 border border-gray-300 rounded-lg</value>
      <webElementGuid>4564b8de-c987-412e-9237-2f39baf8724b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih JurusanIlmu KomputerTeknik ElektroTeknik TelekomunikasiStatistikaTeknik MesinTeknik KomputerFisikaSistem KomputerInformatikaTeknik IndustriHubungan MasyarakatLainnyaSistem InformasiMatematikaTeknik InformatikaManajemen InformatikaTeknik FisikaRekayasa Perangkat LunakTeknik Kimia</value>
      <webElementGuid>9335229c-4695-41ac-b916-95fc8b4f8c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;major&quot;)</value>
      <webElementGuid>bb500397-c64a-4124-99e4-6cb19e19de6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='major']</value>
      <webElementGuid>cca728f1-93c5-4ff1-8071-750e87d3eede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/div[2]/div[2]/div/div[2]/div/select</value>
      <webElementGuid>712b6011-3084-4f34-b3fb-02d81e787495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::select[1]</value>
      <webElementGuid>1d27b0ea-9893-467f-b7e6-4577e556f50c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/preceding::select[1]</value>
      <webElementGuid>7d18a739-2f11-4e30-a772-55392e6fb7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>05b00274-d22c-4f33-a276-b9e8e313bba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'major' and @id = 'major' and (text() = 'Pilih JurusanIlmu KomputerTeknik ElektroTeknik TelekomunikasiStatistikaTeknik MesinTeknik KomputerFisikaSistem KomputerInformatikaTeknik IndustriHubungan MasyarakatLainnyaSistem InformasiMatematikaTeknik InformatikaManajemen InformatikaTeknik FisikaRekayasa Perangkat LunakTeknik Kimia' or . = 'Pilih JurusanIlmu KomputerTeknik ElektroTeknik TelekomunikasiStatistikaTeknik MesinTeknik KomputerFisikaSistem KomputerInformatikaTeknik IndustriHubungan MasyarakatLainnyaSistem InformasiMatematikaTeknik InformatikaManajemen InformatikaTeknik FisikaRekayasa Perangkat LunakTeknik Kimia')]</value>
      <webElementGuid>fe6bf97d-f60d-4e99-ba82-6889d428c2f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
