<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ganti Secondary Email</name>
   <tag></tag>
   <elementGuidId>cda5a899-ffa4-4197-8df7-2f9841928361</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='changeSecondaryEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#changeSecondaryEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65c515e8-23f9-4a56-b4ff-10e2aadbd871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>changeSecondaryEmail</value>
      <webElementGuid>e7b220a6-4101-4fa7-88e1-c7e5d1936b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>968a0c37-530b-4da8-8b05-9c4585a6c85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>changeSecondaryEmail</value>
      <webElementGuid>af027601-ceb6-4068-b666-145099e4fb56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block flex-1 border-0 bg-transparent py-[14px] px-5 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-base sm:leading-6</value>
      <webElementGuid>7aaaf30d-4cbe-473f-ac65-84b5c90883b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan secondary email</value>
      <webElementGuid>dc467946-c3b3-4570-bae3-2f5131c2d2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;changeSecondaryEmail&quot;)</value>
      <webElementGuid>a6ed6ed3-0d69-4a01-ac6b-ca7d23c2cc8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='changeSecondaryEmail']</value>
      <webElementGuid>1382eb4f-9fdc-4652-89a7-c31b2654a62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/form/div/div[5]/div/div/input</value>
      <webElementGuid>7b039cd1-8ada-428d-8e0b-99d0bad4df81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>b21ecd80-a212-489f-b8ff-d975c351e3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'changeSecondaryEmail' and @type = 'email' and @name = 'changeSecondaryEmail' and @placeholder = 'Masukkan secondary email']</value>
      <webElementGuid>ad44e082-331c-4041-bf9e-cc198b31bd47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
