<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Secondary Email</name>
   <tag></tag>
   <elementGuidId>1ab33de3-a742-496b-85a8-b839de91fd9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newSecondaryEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#newSecondaryEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52960520-1ec9-40bc-9f60-baac9d3b5cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newSecondaryEmail</value>
      <webElementGuid>6df07c70-def7-451c-94ff-9f116b6121b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newSecondaryEmail</value>
      <webElementGuid>7a341d9c-ad5a-4f1c-a55c-4c64f804492b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>043bd164-f272-4d5c-88dd-7c8709390e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block flex-1 border-0 bg-transparent py-[14px] px-5 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-base sm:leading-6</value>
      <webElementGuid>1ec9e4f5-2365-4272-90be-790e32cf8dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan secondary email</value>
      <webElementGuid>6a222153-f338-4c11-a15e-ca2a2b653e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newSecondaryEmail&quot;)</value>
      <webElementGuid>2838a836-bc8f-4cf4-a33c-e28cb6253fdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newSecondaryEmail']</value>
      <webElementGuid>b7936b91-3b19-4e3c-ab2a-1f288ee3ad86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/form/div/div[3]/div/div/input</value>
      <webElementGuid>8aacc77d-4216-4bfd-ad29-2f66ee68387d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>28dfab29-3ace-41a2-b9d9-640403c3ac31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'newSecondaryEmail' and @name = 'newSecondaryEmail' and @type = 'email' and @placeholder = 'Masukkan secondary email']</value>
      <webElementGuid>b5f3a98b-8eef-4ca6-822f-2647eaee7c74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
